#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define NO_AUTO_SHIFT_TAB
#define NO_AUTO_SHIFT_ALPHA
#define SERIAL_NUMBER "p6yed/gaYYyw"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 1

#define RGB_MATRIX_STARTUP_SPD 60

